- type: job
  id: Pilot
  name: job-name-pilot
  playTimeTracker: JobPilot
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs
  startingGear: PilotGear
  icon: "JobIconPilot"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PilotGear
  equipment:
    jumpsuit: DWClothingUniformJumpsuitSecPilot
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    head: DWClothingHeadHatBeretPilot
    outerClothing: ClothingOuterArmorBasic
    id: PilotPDA
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckTieRed
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: DWClothingUniformJumpskirtSecPilot
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
